language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
script:
  - composer install
  - vendor/bin/phpunit
after_success:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  - php phpcs.phar -n --standard=PSR1,PSR2 src/
