language: php
php:
  - 5.5
  - 5.6
  - nightly
script:
  - composer install
  - composer require codeclimate/php-test-reporter
  - phpunit --coverage-clover build/logs/clover.xml
after_success:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  - php phpcs.phar -n --standard=PSR1,PSR2 src/