language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
script:
  - composer install
  - composer require codeclimate/php-test-reporter
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - CODECLIMATE_REPO_TOKEN=07757fade9d928f645f52c8208b98b491b8b2a9fe8f1a7f3ca05ae3fcfcd8af9 vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  - php phpcs.phar -n --standard=PSR1,PSR2 src/
