language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
script:
  - composer install
  - phpunit
after_success:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  - php phpcs.phar -n --standard=PSR1,PSR2 src/
